#+title: Types of Expressions
#+HTML_MATHJAX: align: left indent: 2em
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style.css" />
#+OPTIONS: html-style:nil H:1 toc:nil num:nil
#+HTML_LINK_HOME: ../toc.html
The following is a collection of problems which require you to reason
about the types of OCaml expressions.
1. What is the type of ~g~ so that the following expression is
   well-typed?  Can ~g~ be given a polymorphic type?  Also, what is
   the type of the following expression?  Justify your answer.
   #+begin_src ocaml
     let rec f x = g x + g (f x) in f
   #+end_src
2. Suppose that ~h~ is of type ~'a list -> 'a list -> 'a~ and ~k~ is
   of type ~'b -> ('b -> 'b) list~.  Determine the type of the
   following expression.  Justify your answer.
   #+begin_src ocaml
     fun x y -> h x (k y)
   #+end_src
3. Determine the smallest context such that the following expression
   is well-typed.  Also determine the type of the expression.
   #+begin_src ocaml
     let rec f x = f (x + g (f y)) in h (g (x = y)) = f x
   #+end_src
4. Determine the type of the function ~f~.
   #+begin_src ocaml
     let f =
       let rec g lst =
         match lst with
         | 1 :: 1 :: xs -> h xs
         | [] -> true
         | _ -> false
       and h lst =
         match lst with
         | 0 :: xs -> k xs
         | _ -> false
       and k lst = g lst || h lst
       in k
   #+end_src
   Also determine the values of the following expressions:
   + ~f []~
   + ~f [1]~
   + ~f [1;1;0]~
   + ~f [1;1;1;0;0]~
   + ~f [1;1;1;0;0;1;1;0]~
5. Determine the type of the function ~f~.
   #+begin_src ocaml
     let f =
       let rec g lst =
         match lst with
         | true :: false :: xs -> 1 + k xs
         | _ -> 0
       and h lst =
         match lst with
         | true :: xs -> 1 + k xs
         | _ -> 0
       and k lst = max (g lst) (h lst)
       in k
   #+end_src
   Also determine the values of the following expressions:
   + ~f []~
   + ~f [true]~
   + ~f [true;false]~
   + ~f [false;true;true;false]~
   + ~f [true;true;true;false;true]~
6. Determine the type of the function ~x~.
   #+begin_src ocaml
     let x y =
       let x = y in
       let y x = x + 1 in
       let x y = y x in
       x y
   #+end_src
   Also determine the value of ~x 2~.
