#+title: Matrices
#+HTML_MATHJAX: align: left indent: 2em
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style.css" />
#+OPTIONS: html-style:nil H:1 toc:nil num:nil
#+HTML_LINK_HOME: ../toc.html
In this problem you'll build a (very) small interface for matrices.  A
matrix is represented as a record which keeps track of its numbers of
rows and columns, as well as its values, represented as a list of rows
(i.e., a list of lists).  You will implement some error handling by
working with ~result~ values.

#+begin_src ocaml
  type error
    = Uneven_rows
    | Zero_rows
    | Zero_cols
    | Mul_mismatch

  type 'a matrix = {
    num_rows : int ;
    num_cols : int ;
    rows : 'a list list ;
  }
#+end_src

** Constructor

Implement the function
#+begin_src ocaml
  val mk_matrix : 'a list list -> ('a matrix, error) result
#+end_src
so that ~mk_matrix rs~ is a matrix represented by the list of lists
~rs~ if it is valid, or an ~error~ otherwise.  The error conditions
are:

   - if the lengths of the rows in ~rs~ are not all equal, then
     ~mk_matrix~ should return ~Error Uneven_rows~;
   - if ~rs~ is empty, then ~mk_matrix~ should return
     ~Error Zero_rows~;
   - if ~rs~ contains only empty lists, then ~mk_matrix~ should
     return ~Error Zero_cols~.

In other words, ~mk_matrix~ should only return a matrix if ~rs~
represents a nonempty rectangular grid of values.

#+begin_src ocaml
  let l = [[1;2;3];[4;5;6]]
  let rm = mk_matrix l
  let _ = match rm with
    | Ok m ->
      let _ = assert (m.num_rows = 2) in
      let _ = assert (m.num_cols = 3) in
      ()
    | _ -> assert false

  let r = [[1;2;3;4];[1;2;3]]
  let rm' = mk_matrix r
  let _ = match rm' with
    | Ok _ -> assert false
    | Error e -> assert (e = Uneven_rows)
#+end_src

** Traspose

Implement the function
#+begin_src ocaml
  val transpose : 'a matrix -> 'a matrix
#+end_src
so that ~transpose m~ is the [[https://en.wikipedia.org/wiki/Transpose][transpose]] of ~m~.

#+begin_src ocaml
  let _ = match rm with
    | Ok m ->
      let tm = transpose m in
      let _ = assert (tm.num_rows = 3) in
      let _ = assert (tm.num_cols = 2) in
      let _ = assert (tm.rows = [[1;4];[2;5];[3;6]]) in
      ()
    | _ -> assert false
#+end_src

** Multiply

Implement the function
#+begin_src ocaml
  val multiply : float matrix -> float matrix -> (float matrix, error) result
#+end_src
so that ~multiply m n~ is the product of ~m~ and ~n~ (see
[[https://en.wikipedia.org/wiki/Matrix_multiplication][matrix multiplication]])
if it is possible to multiply them.  The error condition:

   - if the number of columns of ~m~ is not the same as the number
     of rows of ~n~, then ~multiply~ should return
     ~Error Mul_mismatch~.

#+begin_src ocaml
  let a =
    { num_rows = 2 ;
      num_cols = 2 ;
      rows = [[1.;2.];[3.;4.]] ;
    }

  let b =
    { num_rows = 1 ;
      num_cols = 2 ;
      rows = [[1.; 2.]] ;
    }

  let _ = assert (multiply a a = Ok {
    num_rows = 2 ;
    num_cols = 2 ;
    rows = [[7.;10.];[15.;22.]] ;
   })

  let _ = assert (multiply a b = Error Mul_mismatch)
#+end_src
