#+title: Valid 1D Paths
#+HTML_MATHJAX: align: left indent: 2em
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../style.css" />
#+OPTIONS: html-style:nil H:1 toc:nil num:nil
#+HTML_LINK_HOME: ../index.html

#+begin_src ocaml
  type dir =
    | Left
    | Right

  type path = int * (dir * int) list
#+end_src

A /path/ represents a sequence of integers from a given starting
point.  For example, the path ~(0, [(Left, 1);(Right, 2);(Right,
3);(Left, 1)])~ represents the sequence

\[
0 \longrightarrow (-1) \longrightarrow 1 \longrightarrow 4 \longrightarrow 3
\]

It's possible for the length-part of a path to be 0 or negative, i.e.,
~(Left, 0)~ stays in place and ~(Left, -1)~ moves /right/ by 1.

We think of a path as being traced out by a point mass on $\mathbb R$
where, by time step $i + 1$, the point mass travels the distance and
direction given by the path at index $i$.

Two paths are /valid/ if it's possible for their point masses to avoid
"phasing through each other" during the execution of each path.  For
example, the paths

\[
0 \longrightarrow 3 \longrightarrow -2
\]

and

\[
5 \longrightarrow 2 \longrightarrow -5
\]

are not valid because their point masses need to phase
through each other to get to the correct positions after 1 time
step, whereas the paths

\[
0 \longrightarrow 6 \longrightarrow -6
\]

and

\[
5 \longrightarrow 7 \longrightarrow -5
\]

are valid because, even though they cover a lot of the same parts of
$\mathbb{R}$, they can travel to each position by each time step
without ever colliding (with some care taken as to their velocity
in between time steps).  If one path is longer than the other, the point
mass of the shorter path is treated as being stationary until the other
path finishes.  For example,

\[
0 \longrightarrow 6
\]

and

\[
5 \longrightarrow 7 \longrightarrow -5
\]

are not valid because in order to get from 7 to -5, the second point
mass has to travel through 6, where the first point mass remains
stationary.

Implement the function
#+begin_src ocaml
  val is_valid : path -> path -> bool
#+end_src
so that ~is_valid (s1, p1) (s2, p2)~ is ~true~ if and only if ~p1~ and ~p2~ are
valid with respect to ~s1~ and ~s2~.

** Examples

#+begin_src ocaml
  let _ = assert (is_valid (0, []) (10, []))

  let p1 = (0, [(Right, 3); (Left, 5)])
  let p2 = (5, [(Left, 3); (Left, 7)])
  let _ = assert (not (is_valid p1 p2))

  let p3 = (0, [(Right, 6); (Left, 12)])
  let p4 = (5, [(Right, 2); (Left, 12)])
  let _ = assert (is_valid p3 p4)

  let p5 = (0, [(Right, 6)])
  let _ = assert (not (is_valid p5 p4))
#+end_src
